package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26

import (
	"context"
	"fmt"
)

// Onboard is the resolver for the onboard field.
func (r *mutationResolver) Onboard(ctx context.Context, input OnboardUserInput) (*OnboardPayload, error) {
	panic(fmt.Errorf("not implemented: Onboard - onboard"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
